spnego_gss_acquire_cred_from() may attempt to free uninitialized pointer
krb5/krb5 pull request #1139
Opened 2020-11-20 15:50 UTC by Sashan

gss_release_iod_set() may attempt to release uninitialized pointer (`amechs`)
if earlier call to `get_available_mechs()` called earlier fails to find
a mechanism.

Initializing local variable `amechs` to `GSS_C_NULL_OID_SET` puts
sufficient mesure in.

2020-11-20 16:51 UTC, frozencemetery requested changes
It looks to me like `gss_get_available_mechs` always initializes `rmechs`.  What's the path to produce uninitialized `amechs` in this code?

2020-11-20 17:38 UTC, greghudson commented
I agree with Robbie that there doesn't seem to be a bug here.  However, if a static analyzer is tripping over this code, it may be reasonable to add a defensive initializer, as we would if `amechs` was released in a cleanup handler.  (It's not, but it is released on either success or failure from get_available_mechs(), which is a little bit unusual.)

2020-11-23 12:43 UTC, Sashan commented
the issue is detected by unit test on Solaris. I don't know why `rmechs` is left uninitialized by `gss_get_available_mechs()`.  Will double check how things work/supposed to work on Solaris.  Let me provide a brief summary of things I know.

The callstack reads as follows:
```
root@foo:/var/tmp/stc-gate/usr/ontest/lib/libgss/gss_api# ./gss.10
Segmentation Fault (core dumped)
root@foo:/var/tmp/stc-gate/usr/ontest/lib/libgss/gss_api# pstack core
core 'core' of 9136:    ./gss.10
 00007fffbbbf30e3 generic_gss_release_oid_set () + 83 (rel_oid_set.c:52)
 00007fffbbc661cc gss_release_oid_set () + 2c (g_rel_oid_set.c:42)
 00007fffbbd413e2 spnego_gss_acquire_cred_from () + 162 (spnego_mech.c:414)
 00007fffbbc06853 gss_add_cred_from () + 5f3 (g_acquire_cred.c:547)
 00007fffbbc05583 gss_acquire_cred_from () + 3c3 (g_acquire_cred.c:195)
 00007fffbbc05177 gss_acquire_cred () + 97 (g_acquire_cred.c:109)
 0000000000402697 main () + 237 (gss.10.c:88)
 0000000000401cb4 ???????? ()
```

The unit test is linked with libs as follows:
```
root@foo:/var/tmp/stc-gate/usr/ontest/lib/libgss/gss_api# ldd gss.10
        libsocket.so.1 =>        /lib/64/libsocket.so.1
        libnsl.so.1 =>   /lib/64/libnsl.so.1
        libgssapi_krb5.so.2 =>   /usr/lib/64/libgssapi_krb5.so.2
        libc.so.1 =>     /lib/64/libc.so.1
        libkrb5.so.3 =>  /usr/lib/amd64/libkrb5.so.3
        libk5crypto.so.3 =>      /usr/lib/amd64/libk5crypto.so.3
        libcom_err.so.3 =>       /usr/lib/amd64/libcom_err.so.3
        libkwarn.so.1 =>         /usr/lib/amd64/libkwarn.so.1
        libkrb5support.so.0 =>   /usr/lib/amd64/libkrb5support.so.0
        libresolv.so.2 =>        /usr/lib/amd64/libresolv.so.2
        libucrypto.so.1 =>       /usr/lib/amd64/libucrypto.so.1
        libelf.so.1 =>   /lib/64/libelf.so.1
        libcryptoutil.so.1 =>    /lib/64/libcryptoutil.so.1
        libbsm.so.1 =>   /lib/64/libbsm.so.1
        libz.so.1 =>     /lib/64/libz.so.1
        libtsol.so.2 =>  /lib/64/libtsol.so.2
        libinetutil.so.1 =>      /lib/64/libinetutil.so.1
```

It looks like `get_available_mechs() fails _(I still need to verify the assumption)_. The code in question reads as follows:
```
 394         /* We will obtain a mechglue credential and wrap it in a
 395          * spnego_gss_cred_id_rec structure.  Allocate the wrapper. */
 396         status = create_spnego_cred(minor_status, mcred, &spcred);
 397         if (status != GSS_S_COMPLETE)
 398                 return (status);
 399 
 400         /*
 401          * Always use get_available_mechs to collect a list of
 402          * mechs for which creds are available.
 403          */
 404         status = get_available_mechs(minor_status, desired_name,
 405                                      cred_usage, cred_store, &mcred,
 406                                      &amechs, time_rec);
 407 
 408         if (actual_mechs && amechs != GSS_C_NULL_OID_SET) {
 409                 (void) gssint_copy_oid_set(&tmpmin, amechs, actual_mechs);
 410         }
 411         (void) gss_release_oid_set(&tmpmin, &amechs);
```

The `gss_release_oid_set()` at line 411 gets always called. However it looks like `amechs` is guaranteed to be initialized iff earlier call to `get_available_mechs()` succeeds:
```
3152 static OM_uint32
3153 get_available_mechs(OM_uint32 *minor_status,
3154         gss_name_t name, gss_cred_usage_t usage,
3155         gss_const_key_value_set_t cred_store,
3156         gss_cred_id_t *creds, gss_OID_set *rmechs, OM_uint32 *time_rec)
3157 {
3158         OM_uint32 major_status = GSS_S_COMPLETE, tmpmin;
3159         gss_OID_set mechs, goodmechs;
.....
3197         }
3198 
3199         if (mechs->count > 0 && major_status == GSS_S_COMPLETE) {
3200                 *rmechs = mechs;
3201         } else {
3202                 (void) gss_release_oid_set(&tmpmin, &mechs);
3203                 *minor_status = ERR_SPNEGO_NO_MECHS_AVAILABLE;
3204                 map_errcode(minor_status);
3205                 if (major_status == GSS_S_COMPLETE)
3206                         major_status = GSS_S_FAILURE;
3207         }
3208 
```

So another option would be to always initialize rmechs to `GSS_C_NULL_OID_SET` in `get_available_mechs()` itself. 

I have poked to `gss.10.c` source code, it looks like it indeed does try to do some fuzzy testing using invalid mechansim names.

2020-11-23 14:15 UTC, Sashan commented
the crash is result of fuzzing done in gss.10 test. I took a look using gdb, which also shows arguments this is what I see:
```
#0  0x00007fffbbbf30e3 in generic_gss_release_oid_set (minor_status=0x7fffbffff044, set=0x7fffbffff038) at /builds/anedvedi/userland/components/krb5/krb5-1.18.3/src/lib/gssapi/generic/rel_oid_set.c:52
#1  0x00007fffbbc661cc in gss_release_oid_set (minor_status=0x7fffbffff044, set=0x7fffbffff038) from /usr/lib/64/libgssapi_krb5.so.2
#2  0x00007fffbbd413e2 in spnego_gss_acquire_cred_from (minor_status=0x7fffbffff2bc, desired_name=0x507400, time_req=4294967295, desired_mechs=0x7fffbffff140, cred_usage=2, cred_store=0x0, output_cred_handle=0x7fffbffff110, 
    actual_mechs=0x0, time_rec=0x0) at /builds/anedvedi/userland/components/krb5/krb5-1.18.3/src/lib/gssapi/spnego/spnego_mech.c:410
#3  0x00007fffbbc06853 in gss_add_cred_from (minor_status=0x7fffbffff2bc, input_cred_handle=0x505c70, desired_name=0x504b40, desired_mech=0x5596d0, cred_usage=2, initiator_time_req=4294967295, acceptor_time_req=4294967295, cred_store=0x0, 
    output_cred_handle=0x0, actual_mechs=0x0, initiator_time_rec=0x0, acceptor_time_rec=0x0) at /builds/anedvedi/userland/components/krb5/krb5-1.18.3/src/lib/gssapi/mechglue/g_acquire_cred.c:547
#4  0x00007fffbbc05583 in gss_acquire_cred_from (minor_status=0x7fffbffff49c, desired_name=0x504b40, time_req=4294967295, desired_mechs=0x504000, cred_usage=2, cred_store=0x0, output_cred_handle=0x7fffbffff490, actual_mechs=0x7fffbffff488, 
    time_rec=0x0) at /builds/anedvedi/userland/components/krb5/krb5-1.18.3/src/lib/gssapi/mechglue/g_acquire_cred.c:195
#5  0x00007fffbbc05177 in gss_acquire_cred (minor_status=0x7fffbffff49c, desired_name=0x504b40, time_req=4294967295, desired_mechs=0x504000, cred_usage=2, output_cred_handle=0x7fffbffff490, actual_mechs=0x7fffbffff488, time_rec=0x0)
    at /builds/anedvedi/userland/components/krb5/krb5-1.18.3/src/lib/gssapi/mechglue/g_acquire_cred.c:109
#6  0x0000000000402697 in main (argc=1, argv=0x7fffbffff518) at gss.10.c:88
```

Note frame number 2, which shows `spnego_gss_acquire_cred_from()`being called with `actual_mechs=0x0`. The `actual_mechs` being `NULL` makes code to bypass `gssint_copy_oid_set()` at line 409 leaving `amechs` uninitialized.

2020-11-23 16:36 UTC, greghudson commented
In the master branch, the first statement in get_available_mechs() is:

        *rmechs = GSS_C_NO_OID_SET;

Is that true for your version of the code?  It was introduced in commit 74132a3b59956db5c43efd2909a14392cfa7289c, so it is present in krb5-1.18 but not krb5-1.17.

2020-11-23 17:10 UTC, Sashan commented
that line is missing in my sources. Looks like it got dropped during the merge with our in-house samba/windows compatibility patch. I'm going to fix merge and will re-rest. Will share follow up update. Thanks for pointing that out.

2020-11-23 17:51 UTC, Sashan commented
I've just tested the fix with proper merge in `get_available_mechs()`. The fixed version reads as follows:
```
3152 static OM_uint32
3153 get_available_mechs(OM_uint32 *minor_status,
3154         gss_name_t name, gss_cred_usage_t usage,
3155         gss_const_key_value_set_t cred_store,
3156         gss_cred_id_t *creds, gss_OID_set *rmechs, OM_uint32 *time_rec)
3157 {
3158         OM_uint32 major_status = GSS_S_COMPLETE, tmpmin;
3159         gss_OID_set mechs, goodmechs;
3160         gss_OID_set_desc except_attrs;
3161         gss_OID_desc attr_oids[3];
3162         char *msinterop = getenv("MS_INTEROP");
3163 
3164         *rmechs = GSS_C_NO_OID_SET;
3165 
3166         attr_oids[0] = *GSS_C_MA_DEPRECATED;
3167         attr_oids[1] = *GSS_C_MA_NOT_DFLT_MECH;
3168         attr_oids[2] = *GSS_C_MA_MECH_NEGO;     /* Exclude ourselves */
3169         except_attrs.count = sizeof(attr_oids) / sizeof(attr_oids[0]);
```

with line 3164, everything works as expected. So this pull request can get closed. Thanks again for all your support.

2020-11-23 20:38 UTC, greghudson commented
Thanks for confirming.

2020-11-23 20:38 UTC, closed without merging