Preserve cred order in memory ccache type
krb5/krb5 pull request #1144
Opened 2020-12-15 17:57 UTC by greghudson

In the memory credential cache type, add new creds to the tail of the
list so that iteration does not reverse the order.

2020-12-15 18:12 UTC, greghudson commented
We sometimes discuss possible heuristics within the ccache code which depend on cred store order.  For instance, these days Heimdal's FILE ccache type doesn't actually make the cache globally visible until you store a non-config cred, at which point it calls rename() to make the cache visible atomically.  The assumption is that the first real cred to be stored is the important one, and that other users of the cache will succeed as long as they can see it.  (One problem with this heuristic is that gss-krb5 proxy cred caches contain two important creds.)

A wildcard for this kind of reasoning is that ccaches are sometimes created by copying a memory ccache, such as when delegated creds are stored with gss_store_cred_into().  Currently the MEMORY ccache type reverses the order of creds when you iterate over it.  In many cases there is only one non-config entry in the cache, but at a minimum the reversal would flip whether the config entries (FAST availability, start_realm, etc.) appear before or after the real cred.

The list management required for this change is very simple and the PR passes tests, but I haven't found a good way to explicitly test it yet.

Although copies from memory caches are the most common, it might be useful to know that cred order is preserved for all ccache types.  I don't know if KEYRING preserves order.  KCM order preservation of course depends on the server implementation.

2020-12-15 20:14 UTC, frozencemetery commented
For sssd-kcm, it looks like cred insertion happens at the front of an internal list, and UUIDs will be returned in list-order - so it would manifest this same behavior as with MEMORY.  However, the list is already doubly-linked, so this could be fixed easily.

For keyring, Linux does not currently document whether it is order-preserving or not.  Currently they keys interface is implemented on top of assoc_array, which states that "The array can be iterated over.  The objects will not necessarily come out in key order."

2020-12-15 20:27 UTC, frozencemetery requested changes
I think `krb5_mcc_remove_cred()` needs to be updated as well.

2020-12-15 21:13 UTC, greghudson commented
> I think krb5_mcc_remove_cred() needs to be updated as well.

I looked at it, but it leaves behind empty nodes (so as not to break iteration), so I don't think it needs to be changed.

2020-12-15 21:25 UTC, frozencemetery approved these changes
Ah, you're right.  All set then :)

2020-12-21 23:03 UTC, greghudson commented
I added a test case.

2020-12-22 16:54 UTC, frozencemetery approved these changes
Test case looks good.

2020-12-22 21:14 UTC, merged